services:
  - type: web
    name: ding-dong-doodle-python-worker
    runtime: docker
    plan: standard
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: WORKER_SECRET
        generateValue: true
      - key: RIG_PYTHON_SCRIPT
        value: /app/arap_animate.py
      - key: PORT
        value: "8000"
